App\Entity\Persona:
      properties:
            nombre:
              - NotBlank: ~
              - Length:
                  min: 5
                  max: 50
                  minMessage: 'The name must be at least {{ limit }} characters long'
                  maxMessage: 'The name cannot be longer than {{ limit }} characters'
                  allowEmptyString: false